# Generated by Django 5.1.5 on 2025-02-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.IntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('patient_id', models.CharField(max_length=100)),
                ('room_num', models.CharField(max_length=100)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
            ],
        ),
    ]
