# Generated by Django 5.1.6 on 2025-03-19 10:11

import api.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('medication', models.CharField(max_length=100)),
                ('start', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('stop', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('time', models.IntegerField(blank=True, null=True)),
                ('initial', models.CharField(blank=True, max_length=5, null=True)),
                ('site', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('sex', models.CharField(max_length=1)),
                ('room_num', models.CharField(max_length=100)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('scenario_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('owner', models.ForeignKey(default=api.models.get_global_user, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario_Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medication')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scenario')),
            ],
            options={
                'unique_together': {('scenario', 'medication')},
            },
        ),
        migrations.AddField(
            model_name='scenario',
            name='medication',
            field=models.ManyToManyField(through='api.Scenario_Medication', to='api.medication'),
        ),
    ]
