# Generated by Django 5.1.6 on 2025-03-24 03:44

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='owner',
            field=models.ForeignKey(default=api.models.get_global_user, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='owner',
            field=models.ForeignKey(default=api.models.get_global_user, on_delete=django.db.models.deletion.CASCADE, related_name='scenario', to=settings.AUTH_USER_MODEL),
        ),
    ]
