# Generated by Django 5.1.6 on 2025-04-16 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_patient_owner_alter_scenario_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='allergies',
            field=models.CharField(default='NKA', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scenario',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='medical_doctor',
            field=models.CharField(default='Dr. Dok Tor', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
