# Generated by Django 5.1.6 on 2025-04-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_scenario_allergies_scenario_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
