# Generated by Django 5.1.5 on 2025-03-17 21:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_patient_id_alter_patient_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.IntegerField()),
                ('medication', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('start', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('stop', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('initial', models.CharField(max_length=5)),
                ('site', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('scenario_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
    ]
