# Generated by Django 5.1.5 on 2025-03-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_medication_scenario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='initial',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='site',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
