# Generated by Django 5.1.6 on 2025-04-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_scenario_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='allergies',
            field=models.CharField(default='NKA', max_length=1000),
        ),
    ]
