# Generated by Django 5.1.6 on 2025-04-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_scenario_allergies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='diagnosis',
            field=models.CharField(default='Fever', max_length=1000),
            preserve_default=False,
        ),
    ]
