# Generated by Django 5.1.6 on 2025-03-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_scenario_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='medication',
        ),
        migrations.AddField(
            model_name='scenario',
            name='medication',
            field=models.ManyToManyField(to='api.medication'),
        ),
    ]
