# Generated by Django 5.1.6 on 2025-04-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_scenario_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='allergies',
            field=models.CharField(blank=True, default='NKA', max_length=1000, null=True),
        ),
    ]
