# Generated by Django 5.1.6 on 2025-04-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_scenario_allergies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='allergies',
            field=models.CharField(default='NKA', max_length=1000),
        ),
    ]
