# Generated by Django 5.1.6 on 2025-03-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_scenario_medication_scenario_medication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medication',
            name='medication',
            field=models.CharField(max_length=100),
        ),
    ]
