# Generated by Django 5.1.6 on 2025-04-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_scenario_allergies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='notes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
