# Generated by Django 5.2 on 2025-05-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_scenario_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
