# Generated by Django 5.2 on 2025-05-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_medication_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='dose',
            field=models.CharField(default='0 mg', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medication',
            name='frequency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='prn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medication',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
