# Generated by Django 5.2 on 2025-05-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_medication_start_medication_start_times_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
