services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app:rw
      - /usr/src/app/node_modules
    depends_on:
      - backend
    networks:
      - freemr-network
    env_file:
      - .env
    command: ["npm", "run", "dev"]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app:rw
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
    networks:
      - freemr-network
    depends_on:
      - postgres
    command: >
      gunicorn api.wsgi:application
      --workers 3
      --bind 0.0.0.0:8000

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - freemr-network

networks:
  freemr-network:
    driver: bridge

volumes:
  postgres_data:
