services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app:rw
      - /usr/src/app/node_modules
    depends_on:
      - backend
    networks:
      - freemr-network
    env_file:
      - .env
    command: ["npm", "run", "dev"]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app:rw
    env_file:
      - .env
    networks:
      - freemr-network
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
networks:
  freemr-network:
    driver: bridge
